### ISSUE TITLE
Add support for windows

### ISSUE THREAD

**Issue by franciscolourenco** [franciscolourenco/done#5]

**Comment by aristidesfl** [comment]
@jbucaran any idea what people on windows are using to display notifications?

**Comment by jbucaran** [comment]
@aristidesfl Not sure, but these couple of hits seemed promising.

* http://stackoverflow.com/questions/12514475/how-can-you-create-pop-up-messages-in-a-batch-script
* http://stackoverflow.com/questions/774175/show-a-popup-message-box-from-a-windows-batch-file

**Comment by aristidesfl** [comment]
@jbucaran do you have any stats on the percentage of users on Windows?
Trying to evaluate if it would be worthwhile to work on this since I never use windows.

**Comment by jbucaran** [comment]
Definitely low. I think you can keep the issue open, but not make it a priority?

**Comment by zhangnew** [comment]
For wsl : https://github.com/Microsoft/WSL/issues/2466

> PS C:\WINDOWS\system32> Install-Module -Name BurntToast

`set -U __done_notification_command 'powershell.exe -command New-BurntToastNotification -Text WSL-ok'`

**Comment by franciscolourenco** [comment]
@zhangnew do you have a proposal on how to integrate this in the package?

**Comment by ohk2kt3t4** [comment]
If being run under WSL:
- can detect if being run under WSL using `grep Microsoft /proc/version`
- can detect if BurntToast is installed using `powershell.exe -command Get-Module -Name Burnt Toast`. (Need to figure out how to get the exit status from this command...)

However the biggest issue is detecting whether or not the terminal window is in the foreground.

**Comment by ammgws** [comment]
AFAIK when running on Windows, `fish` would just be running in something like cygwin or WSL where you cannot get the focused state of the app. However since this script also seems to work with `tmux`, perhaps on Windows notifications could still be sent when using tmux. 

I don't seem to be getting any notifications from detached tmux windows on my linux machine, so first I will debug that and once it is working I will check using Windows and if successful can submit a PR for (limited) Windows support.

**Comment by ammgws** [comment]
Solved with #60.
